// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtSrk0eGJv03IlBIQ-pp6ZA3IpADh65HI',
    appId: '1:255181096684:web:ba96088f46fa76e66387c9',
    messagingSenderId: '255181096684',
    projectId: 'simas-uas-pemob2',
    authDomain: 'simas-uas-pemob2.firebaseapp.com',
    storageBucket: 'simas-uas-pemob2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDYQBF1ix-8UM6CkYamGRWEtUbQ4q6pOk',
    appId: '1:255181096684:android:dda2dcc14d70385e6387c9',
    messagingSenderId: '255181096684',
    projectId: 'simas-uas-pemob2',
    storageBucket: 'simas-uas-pemob2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCqpRJ_YWp6ZTgVcCUZoGUgSANA5e6DA',
    appId: '1:255181096684:ios:239c004ea196ab596387c9',
    messagingSenderId: '255181096684',
    projectId: 'simas-uas-pemob2',
    storageBucket: 'simas-uas-pemob2.firebasestorage.app',
    iosBundleId: 'com.example.uasPemob2Simas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCCqpRJ_YWp6ZTgVcCUZoGUgSANA5e6DA',
    appId: '1:255181096684:ios:239c004ea196ab596387c9',
    messagingSenderId: '255181096684',
    projectId: 'simas-uas-pemob2',
    storageBucket: 'simas-uas-pemob2.firebasestorage.app',
    iosBundleId: 'com.example.uasPemob2Simas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtSrk0eGJv03IlBIQ-pp6ZA3IpADh65HI',
    appId: '1:255181096684:web:5c484d7857984f4a6387c9',
    messagingSenderId: '255181096684',
    projectId: 'simas-uas-pemob2',
    authDomain: 'simas-uas-pemob2.firebaseapp.com',
    storageBucket: 'simas-uas-pemob2.firebasestorage.app',
  );

}